        
services:
  redis:
    container_name: redis-todo
    image: redis
    restart: always 
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./core:/app
      - /app/__pycache__/
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
    expose:
      - "8000"
    depends_on:
      - redis
  nginx:
    image: nginx
    container_name: nginx-todo
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    depends_on:
      - backend
      - redis
  worker-1:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
  beat:
    build: .
    container_name: celery-beat
    command: celery -A core beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
      - worker-1
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://backend:8000
  
  locust:
    image: locustio/locust
    volumes:
      - ./core/locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master


volumes:
  static_volume:
  media_volume:


      
       